const CANVAS_WIDTH = 600,
      CANVAS_HEIGHT = 600;

const TOP_BORDER = 0,
      RIGHT_BORDER = CANVAS_WIDTH,
      BOTTOM_BORDER = CANVAS_HEIGHT,
      LEFT_BORDER = 0;

// eslint-disable-next-line no-magic-numbers
const CANVAS_HORIZONTAL_CENTER = CANVAS_WIDTH / 2,
      // eslint-disable-next-line no-magic-numbers
      CANVAS_VERTICAL_CENTER = CANVAS_HEIGHT / 2;

export {
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  TOP_BORDER,
  RIGHT_BORDER,
  BOTTOM_BORDER,
  LEFT_BORDER,
  CANVAS_HORIZONTAL_CENTER,
  CANVAS_VERTICAL_CENTER,
};
