import { CANVAS_HORIZONTAL_CENTER, BOTTOM_BORDER } from './canvas.js';

const PLAYER_WIDTH = 100,
      PLAYER_HEIGHT = 20;

// eslint-disable-next-line no-magic-numbers
const START_PLAYER_POS_X_OFFSET = -(PLAYER_WIDTH / 2),
      START_PLAYER_POS_Y_OFFSET = -75;

const START_PLAYER_POS_X = CANVAS_HORIZONTAL_CENTER + START_PLAYER_POS_X_OFFSET,
      START_PLAYER_POS_Y = BOTTOM_BORDER + START_PLAYER_POS_Y_OFFSET;

const PLAYER_COLOR = 'red';

export {
  PLAYER_WIDTH,
  PLAYER_HEIGHT,
  START_PLAYER_POS_X_OFFSET,
  START_PLAYER_POS_Y_OFFSET,
  START_PLAYER_POS_X,
  START_PLAYER_POS_Y,
  PLAYER_COLOR,
};
